### ISSUE TITLE
How can I change the version code on Android

### ISSUE THREAD

**Issue by marioshtika** [ionic-team/capacitor-configure#16]
Hello,

from this [example](https://github.com/ionic-team/capacitor-configure/blob/main/examples/basic.yml) I don't see an option on how to change the version code on an Android project.

Following the logic of the API I found this [file](https://github.com/ionic-team/capacitor-configure/blob/main/packages/configure/src/operations/android/version.ts), where I am seeing that the option should be `versionCode`.
I added on my yml file, but it is not updated the version code.

Is this something it is not supported yet? Am I doing something wrong?

Thank you in advance

**Comment by mlynch** [comment]
That should work, will double check in a few days and let you know

**Comment by tobiasmuecksch** [comment]
I can confirm, that this issue exists, as I'm experiencing the same.

The versionCode stays untouched in the manifest file

**Comment by tobiasmuecksch** [comment]
Additionally I have the same issue with iOS. I want to set the build version programatically since I'm not using incremental build Versions. I tried using `buildVersion` but it does not have any effect on the `project.pbxproj` file.

**Comment by mlynch** [comment]
Taking a look today...

**Comment by mlynch** [comment]
The Android versionCode issue be fixed in 1.0.13, can someone verify?

The issue was the android task runners weren't returning their promises so it was basically a race condition which is why I had some trouble reproducing it initially.

**Comment by tobiasmuecksch** [comment]
@mlynch I can confirm, that with version `1.0.13` it works for android. For iOS it's still broken. Should I create a separate issue for iOS?

**Comment by mlynch** [comment]
@tobiasmuecksch no need to but correct, I haven’t looked at that one just yet that will be next

**Comment by mlynch** [comment]
@tobiasmuecksch this one I'm not able to reproduce, `buildNumber` works fine for me and correctly sets `CURRENT_PROJECT_VERSION` in the `pbxproj`. Maybe there's something unique about your setup? If so could you file an issue with more info that might be helpful?

<img width="766" alt="image" src="https://user-images.githubusercontent.com/11214/143781635-b0097f09-3dfa-4918-847c-4f31d50a14fc.png">

**Comment by tobiasmuecksch** [comment]
@mlynch Thank you for investigating. I've found out what the issue is in my case. I've created a ticket for it https://github.com/ionic-team/capacitor-configure/issues/20

**Comment by marioshtika** [comment]
Hello @mlynch 

Thank you very much. I can confirm this is working in `1.0.13` 👍 

Both on Android and iOS.
